### ISSUE TITLE
Remove redundant prefixes from fields in `PanelCfg` schema interface

### ISSUE THREAD

**Issue by sdboyer** [grafana/kindsys#6]
This is the current `PanelCfg` schema interface contract that all `PanelCfg` composable kinds must follow:

https://github.com/grafana/kindsys/blob/b1fe864ba880ea7aa4544e7cbf810856d40db56d/schema_interface.cue#L98-L109

Having the `Panel` prefix is redundant. `Options` and `FieldConfig` would be perfectly sufficient.

The change here is simple enough while we're effectively in pre-launch mode:

- [x] All panel implementations in grafana/grafana will need to be updated
- [x] Names of generated types within panel plugins will need to be updated as well
- [ ] Grok will need to be regenerated.

Sooner we do this one, the better, because it's a _wildly_ breaking change 😄

**Comment by undef1nd** [comment]
Requires the following PRs to be merged:
- Grafana https://github.com/grafana/grafana/pull/68034
- Kindsys https://github.com/grafana/kindsys/pull/7
- This PR needs to be updated to use kindsys main as a dependency in Grafana https://github.com/grafana/grafana/pull/65297

**Comment by sdboyer** [comment]
Whoops, in skirting around the lineage flattening PR, i had to modify ordering of these merges. grafana is now on an off-main commit for kindsys, and will have to stay there until we fix grafana/grafana#68034
